# https://docs.readthedocs.io/en/latest/config-file/index.html
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    post_checkout:
      - git fetch --unshallow

formats:
  - htmlzip
  - epub

python:
  install:
    - method: pip
      path: .
    - requirements: requirements/docs.txt

sphinx:
  fail_on_warning: true
  configuration: docs/source/conf.py
